db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: CHANGEMEA$AP!
    MYSQL_DATABASE: exile
    MYSQL_USER: exile
    MYSQL_PASSWORD: exile
  volumes:
    - ./arma3/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    - ./arma3/docker-var-mysql:/var/lib/mysql

server:
  image: timelf123/arma3
  volumes:
    - ./arma3/keys:/arma3/keys
    - ./arma3/mods:/arma3/mods
    - ./arma3/mpmissions:/arma3/mpmissions
    - ./arma3/server:/server
    - ./params:/arma3/params
    - ./arma3/profiles:/profiles
  links:
    - db
  ports:
    - "2302:2302/udp"
    - "2303:2303/udp"
    - "2304:2304/udp"
    - "2305:2305/udp"
