store:
  build: ./exile
  image: timelf123/arma3-exile:1.0.2
  volumes:
    - ./exile/profiles:/profiles
    - ./exile/main.cfg:/server/main.cfg
    - ./exile/basic.cfg:/server/basic.cfg
    - ./exile/params:/arma3/params
    - /docker-entrypoint-initdb.d/
    - /var/lib/mysql

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: StinkyTofu12345
    MYSQL_DATABASE: exile
    MYSQL_USER: exile
    MYSQL_PASSWORD: exile
  volumes_from:
    - store

server:
  image: timelf123/arma3
  volumes_from:
    - store
  links:
    - db
  ports:
    - "2302/udp"
    - "2303/udp"
    - "2304/udp"
    - "2305/udp"
